[project]
name = "can2mqtt"
version = "0.0.1"
authors = [
    {name="Mariusz Kryński", email="mrk@sed.pl"}
]
requires-python = ">=3.8"

dependencies = [
    "canopen@git+https://github.com/sveinse/canopen-asyncio",
    "asyncio-mqtt",
    "pyserial",
    "coloredlogs",
]

[project.scripts]  # Optional
can2mqtt = "main:main"

[project.optional-dependencies]
dev = [
    "black"
]
