<<: !include {file: common.yaml}

wifi:
  <<: !include {file: wifi.yaml}
  manual_ip:
    static_ip: 192.168.1.201
    subnet: 255.255.255.0
    gateway: 192.168.1.1

esphome:
  name: can-node-1
  libraries:
    #- file:///home/mrk/priv/esphome-can/config/canopen-stack
    - canopenstack=https://github.com/mrk-its/canopen-stack
      #- file:///home/mrk/priv/esphome-can/config/cfg

can_gateway:
  id: can_gate
  canbus_id: can_bus
  node_id: 5
  entities:
    - id: boot
      index: 1
      tpdo: 0
    - id: blue_led
      index: 2
      tpdo: 0
    - id: cover1
      index: 5
      tpdo: 0
    - id: uptime_sensor
      index: 3
      tpdo: 0
    - id: cover2
      index: 6

sensor:
  - platform: uptime
    id: uptime_sensor
    name: "Uptime1"
    update_interval: 5sec
    internal: true

binary_sensor:
  - platform: gpio
    name: "Boot1"
    id: boot
    internal: true
    filters:
      - delayed_off: 2000ms
    pin:
      number: 0
      inverted: true

switch:
  - platform: gpio
    name: "Led1"
    id: blue_led
    internal: true
    pin: 2


cover:
  - platform: time_based
    name: "Cover1"
    id: cover1
    internal: true
    device_class: shutter
    has_built_in_endstop: true
    open_action:
      - logger.log: open_action
    open_duration: 10s
    close_action:
      - logger.log: close_action
    close_duration: 10s
    stop_action:
      - logger.log: stop_action

  - platform: time_based
    name: "Cover2"
    id: cover2
    internal: true
    device_class: shutter
    has_built_in_endstop: true
    open_action:
      - logger.log: open_action
    open_duration: 10s
    close_action:
      - logger.log: close_action
    close_duration: 10s
    stop_action:
      - logger.log: stop_action
