<<: !include {file: common.yaml}

wifi:
  <<: !include {file: wifi.yaml}
  manual_ip:
    static_ip: 192.168.1.201
    subnet: 255.255.255.0
    gateway: 192.168.1.1

esphome:
  name: can-node-1
  includes:
    - can_utils.h
    - can_binary_sensor.h
    - can_switch.h
    - can_sensor.h
    - can_cover.h
  on_boot:
    priority: 500
    then:
      - lambda: |
          can_configure_switch(id(can_bus), id(blue_led), 1);
          can_configure_sensor(id(can_bus), id(uptime_sensor), 2);
          can_configure_binary_sensor(id(can_bus), id(boot), 3);
          can_configure_cover(id(can_bus), id(test_cover), 4 );

canbus:
  - platform: esp32_can
    id: can_bus
    rx_pin: GPIO22
    tx_pin: GPIO23
    can_id: 1
    bit_rate: 125kbps
    use_extended_id: true

    on_frame:
      - can_id: 0
        can_id_mask: 0
        use_extended_id: true
        then:
          - lambda: can_cmd_message(can_id, remote_transmission_request, x);

sensor:
  - platform: uptime
    id: uptime_sensor
    name: "Uptime1"
    update_interval: 5sec
    internal: true

binary_sensor:
  - platform: gpio
    name: "Boot1"
    id: boot
    pin:
      number: 0
      inverted: true

switch:
  - platform: gpio
    name: "Led1"
    id: blue_led
    internal: true
    pin: 2

cover:
  - platform: time_based
    name: "CanCover"
    id: test_cover
    internal: true
    device_class: shutter
    has_built_in_endstop: true
    open_action:
      - logger.log: open_action
    open_duration: 10s
    close_action:
      - logger.log: close_action
    close_duration: 10s
    stop_action:
      - logger.log: stop_action
